---
before_install:
  - gem update --system
  - gem update bundler
language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-9.1.17.0
  - jruby-9.2.0.0
env:
  global:
    NOBENCHMARK=1
script: rake
