---
before_install:
  - gem update --system
  - gem update bundler
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-9.1.17.0
  - jruby-9.2.0.0
env:
  global:
    NOBENCHMARK=1
script: rake
