---
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before
language: ruby
notifications:
  email:
  - drbrain@segment7.net
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
script: rake test
after_script:
- rake check_manifest
